### ISSUE TITLE
CodingBat - Warmup-1

### ISSUE THREAD

**Issue by thedevjournal** [thedevjournal/code-challenges-java#1]
## Tasklist
```[tasklist]
### Tasks
- [ ] backAround - https://github.com/thedevjournal/code-challenges-java/issues/18
- [ ] close10 - https://github.com/thedevjournal/code-challenges-java/issues/19
- [ ] delDel - https://github.com/thedevjournal/code-challenges-java/issues/20
- [ ] diff21 - https://github.com/thedevjournal/code-challenges-java/issues/21
- [ ] endUp - https://github.com/thedevjournal/code-challenges-java/issues/22
- [ ] everyNth - https://github.com/thedevjournal/code-challenges-java/issues/23
- [ ] front22 - https://github.com/thedevjournal/code-challenges-java/issues/24
- [ ] front3 - https://github.com/thedevjournal/code-challenges-java/issues/25
- [ ] frontBack - https://github.com/thedevjournal/code-challenges-java/issues/26
- [ ] hasTeen - https://github.com/thedevjournal/code-challenges-java/issues/27
- [ ] icyHot - https://github.com/thedevjournal/code-challenges-java/issues/28
- [ ] in1020 - https://github.com/thedevjournal/code-challenges-java/issues/29
- [ ] in3050 - https://github.com/thedevjournal/code-challenges-java/issues/30
- [ ] intMax - https://github.com/thedevjournal/code-challenges-java/issues/31
- [ ] lastDigit - https://github.com/thedevjournal/code-challenges-java/issues/32
- [ ] loneTeen - https://github.com/thedevjournal/code-challenges-java/issues/33
- [ ] makes10 - https://github.com/thedevjournal/code-challenges-java/issues/34
- [ ] max1020 - https://github.com/thedevjournal/code-challenges-java/issues/35
- [ ] missingChar - https://github.com/thedevjournal/code-challenges-java/issues/36
- [ ] mixStart - https://github.com/thedevjournal/code-challenges-java/issues/37
- [ ] monkeyTrouble - https://github.com/thedevjournal/code-challenges-java/issues/38
- [ ] nearHundred - https://github.com/thedevjournal/code-challenges-java/issues/39
- [ ] notString - https://github.com/thedevjournal/code-challenges-java/issues/40
- [ ] or35 - https://github.com/thedevjournal/code-challenges-java/issues/41
- [ ] parrotTrouble - https://github.com/thedevjournal/code-challenges-java/issues/42
- [ ] posNeg - https://github.com/thedevjournal/code-challenges-java/issues/43
- [ ] sleepIn - https://github.com/thedevjournal/code-challenges-java/issues/44
- [ ] startHi - https://github.com/thedevjournal/code-challenges-java/issues/45
- [ ] startOz - https://github.com/thedevjournal/code-challenges-java/issues/46
- [ ] stringE - https://github.com/thedevjournal/code-challenges-java/issues/47
- [ ] sumDouble - https://github.com/thedevjournal/code-challenges-java/issues/48
```

## Issues in the Epic
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [x] #48
