### ISSUE TITLE
CodingBat - Warmup-2

### ISSUE THREAD

**Issue by thedevjournal** [thedevjournal/code-challenges-java#2]
## Tasklist
```[tasklist]
### Tasks
- [ ] altPairs - https://github.com/thedevjournal/code-challenges-java/issues/49
- [ ] array123 - https://github.com/thedevjournal/code-challenges-java/issues/50
- [ ] array667 - https://github.com/thedevjournal/code-challenges-java/issues/51
- [ ] arrayCount9 - https://github.com/thedevjournal/code-challenges-java/issues/52
- [ ] arrayFront9 - https://github.com/thedevjournal/code-challenges-java/issues/53
- [ ] countXX - https://github.com/thedevjournal/code-challenges-java/issues/54
- [ ] doubleX - https://github.com/thedevjournal/code-challenges-java/issues/55
- [ ] frontTimes - https://github.com/thedevjournal/code-challenges-java/issues/56
- [ ] has271 - https://github.com/thedevjournal/code-challenges-java/issues/57
- [ ] last2 - https://github.com/thedevjournal/code-challenges-java/issues/58
- [ ] noTriples - https://github.com/thedevjournal/code-challenges-java/issues/59
- [ ] stringBits - https://github.com/thedevjournal/code-challenges-java/issues/60
- [ ] stringMatch - https://github.com/thedevjournal/code-challenges-java/issues/61
- [ ] stringSplosion - https://github.com/thedevjournal/code-challenges-java/issues/62
- [ ] stringTimes - https://github.com/thedevjournal/code-challenges-java/issues/63
- [ ] stringX - https://github.com/thedevjournal/code-challenges-java/issues/64
- [ ] stringYak - https://github.com/thedevjournal/code-challenges-java/issues/65
```

## Issues in the Epic
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #57
- [x] #58
- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63
- [x] #64
- [x] #65
