### ISSUE TITLE
CodingBat - String-1

### ISSUE THREAD

**Issue by thedevjournal** [thedevjournal/code-challenges-java#3]
## Tasklist
```[tasklist]
### Tasks
- [x] atFirst - https://github.com/thedevjournal/code-challenges-java/issues/66
- [x] comboString - https://github.com/thedevjournal/code-challenges-java/issues/67
- [x] conCat - https://github.com/thedevjournal/code-challenges-java/issues/68
- [x] deFront - https://github.com/thedevjournal/code-challenges-java/issues/69
- [x] endsLy - https://github.com/thedevjournal/code-challenges-java/issues/70
- [x] extraEnd - https://github.com/thedevjournal/code-challenges-java/issues/71
- [x] extraFront - https://github.com/thedevjournal/code-challenges-java/issues/72
- [x] firstHalf - https://github.com/thedevjournal/code-challenges-java/issues/73
- [x] firstTwo - https://github.com/thedevjournal/code-challenges-java/issues/74
- [x] frontAgain - https://github.com/thedevjournal/code-challenges-java/issues/75
- [x] hasBad - https://github.com/thedevjournal/code-challenges-java/issues/76
- [x] helloName - https://github.com/thedevjournal/code-challenges-java/issues/77
- [x] lastChars - https://github.com/thedevjournal/code-challenges-java/issues/78
- [x] lastTwo - https://github.com/thedevjournal/code-challenges-java/issues/79
- [x] left2 - https://github.com/thedevjournal/code-challenges-java/issues/80
- [x] makeAbba - https://github.com/thedevjournal/code-challenges-java/issues/81
- [x] makeOutWord - https://github.com/thedevjournal/code-challenges-java/issues/82
- [x] makeTags - https://github.com/thedevjournal/code-challenges-java/issues/83
- [x] middleThree - https://github.com/thedevjournal/code-challenges-java/issues/84
- [x] middleTwo - https://github.com/thedevjournal/code-challenges-java/issues/85
- [x] minCat - https://github.com/thedevjournal/code-challenges-java/issues/86
- [x] nonStart - https://github.com/thedevjournal/code-challenges-java/issues/87
- [x] nTwice - https://github.com/thedevjournal/code-challenges-java/issues/88
- [x] right2 - https://github.com/thedevjournal/code-challenges-java/issues/89
- [x] seeColor - https://github.com/thedevjournal/code-challenges-java/issues/90
- [x] startWord - https://github.com/thedevjournal/code-challenges-java/issues/91
- [x] theEnd - https://github.com/thedevjournal/code-challenges-java/issues/92
- [x] twoChar - https://github.com/thedevjournal/code-challenges-java/issues/93
- [x] withouEnd2 - https://github.com/thedevjournal/code-challenges-java/issues/94
- [x] without2 - https://github.com/thedevjournal/code-challenges-java/issues/95
- [x] withoutEnd - https://github.com/thedevjournal/code-challenges-java/issues/96
- [x] withoutX2 - https://github.com/thedevjournal/code-challenges-java/issues/97
- [x] withoutX - https://github.com/thedevjournal/code-challenges-java/issues/98
```

## Issues in the Epic
- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [x] #85
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
