### ISSUE TITLE
CodingBat - Array-1

### ISSUE THREAD

**Issue by thedevjournal** [thedevjournal/code-challenges-java#4]
## Tasklist
```[tasklist]
### Tasks
- [x] biggerTwo - https://github.com/thedevjournal/code-challenges-java/issues/99
- [x] commonEnd - https://github.com/thedevjournal/code-challenges-java/issues/100
- [x] double23 - https://github.com/thedevjournal/code-challenges-java/issues/101
- [x] firstLast6 - https://github.com/thedevjournal/code-challenges-java/issues/102
- [x] fix23 - https://github.com/thedevjournal/code-challenges-java/issues/103
- [x] front11 - https://github.com/thedevjournal/code-challenges-java/issues/104
- [x] frontPiece - https://github.com/thedevjournal/code-challenges-java/issues/105
- [x] has23 - https://github.com/thedevjournal/code-challenges-java/issues/106
- [x] make2 - https://github.com/thedevjournal/code-challenges-java/issues/107
- [x] makeEnds - https://github.com/thedevjournal/code-challenges-java/issues/108
- [x] makeLast - https://github.com/thedevjournal/code-challenges-java/issues/109
- [x] makeMiddle - https://github.com/thedevjournal/code-challenges-java/issues/110
- [x] makePi - https://github.com/thedevjournal/code-challenges-java/issues/111
- [x] maxEnd3 - https://github.com/thedevjournal/code-challenges-java/issues/112
- [x] maxTriple - https://github.com/thedevjournal/code-challenges-java/issues/113
- [x] middleWay - https://github.com/thedevjournal/code-challenges-java/issues/114
- [x] midThree - https://github.com/thedevjournal/code-challenges-java/issues/115
- [x] no23 - https://github.com/thedevjournal/code-challenges-java/issues/116
- [x] plusTwo - https://github.com/thedevjournal/code-challenges-java/issues/117
- [x] reverse3 - https://github.com/thedevjournal/code-challenges-java/issues/118
- [x] rotateLeft3 - https://github.com/thedevjournal/code-challenges-java/issues/119
- [x] sameFirstLast - https://github.com/thedevjournal/code-challenges-java/issues/120
- [x] start1 - https://github.com/thedevjournal/code-challenges-java/issues/121
- [x] sum2 - https://github.com/thedevjournal/code-challenges-java/issues/122
- [x] sum3 - https://github.com/thedevjournal/code-challenges-java/issues/123
- [x] swapEnds - https://github.com/thedevjournal/code-challenges-java/issues/124
- [x] unlucky1 - https://github.com/thedevjournal/code-challenges-java/issues/125
```

## Issues in the Epic
- [x] #99
- [x] #100
- [x] #101
- [x] #102
- [x] #103
- [x] #104
- [x] #105
- [x] #106
- [x] #107
- [x] #108
- [x] #109
- [x] #110
- [x] #111
- [x] #112
- [x] #113
- [x] #114
- [x] #115
- [x] #116
- [x] #117
- [x] #118
- [x] #119
- [x] #120
- [x] #121
- [x] #122
- [x] #123
- [x] #124
- [x] #125
