### ISSUE TITLE
CodingBat - Logic-1

### ISSUE THREAD

**Issue by thedevjournal** [thedevjournal/code-challenges-java#5]
## Tasklist
```[tasklist]
### Tasks
- [x] alarmClock - https://github.com/thedevjournal/code-challenges-java/issues/126
- [x] answerCell - https://github.com/thedevjournal/code-challenges-java/issues/127
- [x] blueTicket - https://github.com/thedevjournal/code-challenges-java/issues/128
- [x] caughtSpeeding - https://github.com/thedevjournal/code-challenges-java/issues/129
- [x] cigarParty - https://github.com/thedevjournal/code-challenges-java/issues/130
- [x] dateFashion - https://github.com/thedevjournal/code-challenges-java/issues/131
- [x] fizzString2 - https://github.com/thedevjournal/code-challenges-java/issues/132
- [x] fizzString - https://github.com/thedevjournal/code-challenges-java/issues/133
- [x] greenTicket - https://github.com/thedevjournal/code-challenges-java/issues/134
- [x] in1To10 - https://github.com/thedevjournal/code-challenges-java/issues/135
- [x] inOrderEqual - https://github.com/thedevjournal/code-challenges-java/issues/136
- [x] inOrder - https://github.com/thedevjournal/code-challenges-java/issues/137
- [x] lastDigit - https://github.com/thedevjournal/code-challenges-java/issues/138
- [x] less20 - https://github.com/thedevjournal/code-challenges-java/issues/139
- [x] lessBy10 - https://github.com/thedevjournal/code-challenges-java/issues/140
- [x] love6 - https://github.com/thedevjournal/code-challenges-java/issues/141
- [x] maxMod5 - https://github.com/thedevjournal/code-challenges-java/issues/142
- [x] more20 - https://github.com/thedevjournal/code-challenges-java/issues/143
- [x] nearTen - https://github.com/thedevjournal/code-challenges-java/issues/144
- [x] old35 - https://github.com/thedevjournal/code-challenges-java/issues/145
- [x] redTicket - https://github.com/thedevjournal/code-challenges-java/issues/146
- [x] shareDigit - https://github.com/thedevjournal/code-challenges-java/issues/147
- [x] sortaSum - https://github.com/thedevjournal/code-challenges-java/issues/148
- [x] specialEleven - https://github.com/thedevjournal/code-challenges-java/issues/149
- [x] squirrelPlay - https://github.com/thedevjournal/code-challenges-java/issues/150
- [x] sumLimit - https://github.com/thedevjournal/code-challenges-java/issues/151
- [x] teaParty - https://github.com/thedevjournal/code-challenges-java/issues/152
- [x] teenSum - https://github.com/thedevjournal/code-challenges-java/issues/153
- [x] twoAsOne - https://github.com/thedevjournal/code-challenges-java/issues/154
- [x] withoutDoubles - https://github.com/thedevjournal/code-challenges-java/issues/155
```

## Issues in the Epic
- [x] #126
- [x] #127
- [x] #128
- [x] #129
- [x] #130
- [x] #131
- [x] #132
- [x] #133
- [x] #134
- [x] #135
- [x] #136
- [x] #137
- [x] #138
- [x] #139
- [x] #140
- [x] #141
- [x] #142
- [x] #143
- [x] #144
- [x] #145
- [x] #146
- [x] #147
- [x] #148
- [x] #149
- [x] #150
- [x] #151
- [x] #152
- [x] #153
- [x] #154
- [x] #155
