### ISSUE TITLE
CodingBat - String-2

### ISSUE THREAD

**Issue by thedevjournal** [thedevjournal/code-challenges-java#7]
## Tasklist
```[tasklist]
### Tasks
- [ ] bobThere - https://github.com/thedevjournal/code-challenges-java/issues/165
- [ ] catDog - https://github.com/thedevjournal/code-challenges-java/issues/166
- [ ] countCode - https://github.com/thedevjournal/code-challenges-java/issues/167
- [ ] countHi - https://github.com/thedevjournal/code-challenges-java/issues/168
- [ ] doubleChar - https://github.com/thedevjournal/code-challenges-java/issues/169
- [ ] endOther - https://github.com/thedevjournal/code-challenges-java/issues/170
- [ ] getSandwich - https://github.com/thedevjournal/code-challenges-java/issues/171
- [ ] mixString - https://github.com/thedevjournal/code-challenges-java/issues/172
- [ ] oneTwo - https://github.com/thedevjournal/code-challenges-java/issues/173
- [ ] plusOut - https://github.com/thedevjournal/code-challenges-java/issues/174
- [ ] prefixAgain - https://github.com/thedevjournal/code-challenges-java/issues/175
- [ ] repeatEnd - https://github.com/thedevjournal/code-challenges-java/issues/176
- [ ] repeatFront - https://github.com/thedevjournal/code-challenges-java/issues/177
- [ ] repeatSeparator - https://github.com/thedevjournal/code-challenges-java/issues/178
- [ ] sameStarChar - https://github.com/thedevjournal/code-challenges-java/issues/179
- [ ] starOut - https://github.com/thedevjournal/code-challenges-java/issues/180
- [ ] wordEnds - https://github.com/thedevjournal/code-challenges-java/issues/181
- [ ] xyBalance - https://github.com/thedevjournal/code-challenges-java/issues/182
- [ ] xyzMiddle - https://github.com/thedevjournal/code-challenges-java/issues/183
- [ ] xyzThere - https://github.com/thedevjournal/code-challenges-java/issues/184
- [ ] zipZap - https://github.com/thedevjournal/code-challenges-java/issues/185
```

## Issues in the Epic
- [ ] #165
- [ ] #166
- [ ] #167
- [ ] #168
- [ ] #169
- [ ] #170
- [ ] #171
- [ ] #172
- [ ] #173
- [ ] #174
- [ ] #175
- [ ] #176
- [ ] #177
- [ ] #178
- [ ] #179
- [ ] #180
- [ ] #181
- [ ] #182
- [ ] #183
- [ ] #184
- [ ] #185
